FROM ontresearch/dorado@sha256:8c0cdf8d4dfb3ffbbc34782affdcb215c0d1dfaa1372f1672b264064dd0d8e5a

LABEL maintainer="bioinformatics@age.mpg.de"
LABEL org.opencontainers.image.source="https://github.com/nanoporetech/dorado"
LABEL org.opencontainers.image.version="2.0.1"
