#!/bin/bash

set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
tool=$(echo ${repoName} | awk -F/ '{print $2}' )

cd ${DOCKER_REPO}/${DOCKER_TAG}

docker build -t mpgagebioinformatics/${IMAGE_NAME} .
docker push mpgagebioinformatics/${IMAGE_NAME}