#!/bin/bash

set -e

TOOL=$( echo ${DOCKER_TAG} | awk -F- '{ print $1}' )
DOCKER_TAG=$( echo ${DOCKER_TAG} | awk -F- '{ print $2}' )

cd ${TOOL}/${DOCKER_TAG}

docker build -t mpgagebioinformatics/${TOOL}:${DOCKER_TAG} .
docker push mpgagebioinformatics/${TOOL}:${DOCKER_TAG}